baseurl = "https://example.org/"
languageCode = "en-us"
title = "DEVYZER  CRUD Genereator Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Devyzer"
	description = "Speed && flexibility"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/devyzer"

	version = "1.0.0"
#	logo = "images/logo.png"
	logo = "images/devyzer.jpg"
#	logo = "images/tn.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "green"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "https://github.com/devyzer"
	email   = ""


[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

[[menu.main]]
    	name   = "CRUD Generator"
    	url    = "generator/"
    	weight = 5

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10


[[menu.main]]
    name   = "File Config "
    url    = "configration/"
    weight = 15

    [[menu.main]]
        name   = "Fields Config "
        url    = "fields/"
        weight = 17

          [[menu.main]]
                name   = "Fields Sample "
                url    = "fields-sample/"
                weight = 18


         [[menu.main]]
                name   = "Realationship Config "
                 	url    = "relation/"
                 	weight = 19








[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
